document.getElementById('btnClick').onclick = () => {
let input = document.getElementById("userInput").value;
  document.getElementById("output").value = RemoveFiller(input)
function RemoveFiller(text){
  output = text.replace(String(iterator()), "")
  return output
}
function iterator(){
  for (let i = 0; i < fillerWords.length; i++) {
    return fillerWords[i]
  } 
}}
const fillerWords = [
  "absolutely",
  "actual",
  "actually",
  "amazing",
  "anyway",
  "apparently",
  "approximately",
  "badly",
  "basically",
  "begin",
  "certainly",
  "clearly",
  "completely",
  "definitely",
  "easily",
  "effectively",
  "entirely",
  "especially",
  "essentially",
  "exactly",
  "extremely",
  "fairly",
  "frankly",
  "frequently",
  "fully",
  "generally",
  "hardly",
  "heavily",
  "highly",
  "hopefully",
  "just",
  "largely",
  "like",
  "literally",
  "maybe",
  "might",
  "most",
  "mostly",
  "much",
  "necessarily",
  "nicely",
  "obviously",
  "ok",
  "okay",
  "particularly",
  "perhaps",
  "possibly",
  "practically",
  "primarily",
  "probably",
  "precisely",
  "quite",
  "rather",
  "real",
  "really",
  "relatively",
  "right",
  "seriously",
  "significantly",
  "simply",
  "slightly",
  "so",
  "specifically",
  "start",
  "strongly",
  "stuff",
  "surely",
  "things",
  "too",
  "totally",
  "truly",
  "try",
  "typically",
  "ultimately",
  "usually",
  "very",
  "virtually",
  "whatever",
  "well",
  "whenever",
  "wherever",
  "whoever",
  "widely",
]